root = "."
tmp_dir = "tmp"

[build]
  cmd = "CGO_ENABLED=1 go build -o ./tmp/server cmd/server/main.go"
  bin = "./tmp/server"
  full_bin = "APP_ENV=dev ./tmp/server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  include_dir = []
  exclude_file = []
  log = "air.log"
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
