# Copyright (c) 2025 Bouali Consulting Inc.
# Author: Kaiss Bouali (kaissb)
# Company: Bouali Consulting Inc.
# GitHub: https://github.com/kaissb

# Development stage
FROM golang:1.24-alpine

WORKDIR /app

# Install build tools including gcc for cgo
RUN apk add --no-cache build-base

# Copy module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Development stage rest of the application source
COPY . .

# Expose the port
EXPOSE 8080

# Run the app with air for live reload
CMD ["air", "-c", ".air.toml"]
